version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-python-thumbnail"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-hpzcg5u9pr6i"
s3_prefix = "sam-python-thumbnail"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
