AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates S3 Bucket to host data for API Gateway
  Creates DynamoDB to store data posted from API Gateway
  Creates Lambdas that are triggered by API Gateway

Globals:
  Function:
    Timeout: 15

Resources: