AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Creates S3 Bucket to host data for API Gateway
  Creates DynamoDB to store data posted from API Gateway
  Creates Lambdas that are triggered by API Gateway

Parameters:

AccountId:
  Type: String
  Description: Account ID

Region:
  Type: String
  Description: Account Region

LogLevel:
  Type: String
  Description: Logger Level

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  AddTransaction:
    Type: AWS::ServerlessFunction
    Properties:
      FunctionName: AddTransaction
      Handler: add_transaction.lambda_handler
      Runtime: python3.9
      Role: "arn:aws:iam::${AccountId}:role/{roleName}"
      CodeUri: ../functions/
  GetTransaction:
    Type: AWS::ServerlessFunction
    Properties:
      FunctionName: GetTransaction
      Handler: get_transaction.lambda_handler
      Runtime: python3.9
      Role: "arn:aws:iam::${AccountId}:role/{roleName}"
      CodeUri: ../functions/
  GetTransactions:
    Type: AWS::ServerlessFunction
    Properties:
      FunctionName: GetTransactions
      Handler: get_transactions.lambda_handler
      Runtime: python3.9
      Role: "arn:aws:iam::${AccountId}:role/{roleName}"
      CodeUri: ../functions/
  DeleteTransaction:
    Type: AWS::ServerlessFunction
    Properties:
      FunctionName: DeleteTransaction
      Handler: delete_transaction.lambda_handler
      Runtime: python3.9
      Role: "arn:aws:iam::${AccountId}:role/{roleName}"
      CodeUri: ../functions/